/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/yCz4sdWzPvB
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import Link from "next/link"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    (<div key="1" className="bg-gray-50 dark:bg-gray-950">
      <div className="border-b border-gray-200 dark:border-gray-800">
        <div className="container px-4 py-2 md:py-3">
          <nav
            className="flex items-center space-x-4 text-xs font-medium tracking-wide justify-end">
            <Link
              className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#">
              Home
            </Link>
            <Link
              className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#">
              About
            </Link>
            <Link
              className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#">
              Services
            </Link>
            <Link
              className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="#">
              Blog
            </Link>
            <Link
              className="text-gray-500 hover:text-gray-900 dark:text-gray-400 dark:hover:text-gray-50"
              href="contact">
              Contact
            </Link>
          </nav>
        </div>
      </div>
      <header className="py-16 md:py-24 lg:py-32">
        <div
          className="container flex flex-col items-center justify-center gap-4 px-4 text-center md:gap-10 md:px-6">
          <div className="space-y-3">
            <h1 className="text-4xl font-bold tracking-tighter sm:text-5xl md:text-6xl">Get Out There</h1>
            <p
              className="mx-auto max-w-[600px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Your mental health matters. We're here to help you on your journey to a healthier mind.
            </p>
          </div>
          <div className="grid w-full grid-cols-1 gap-4 md:grid-cols-3 md:gap-0">
            <Link
              className="inline-flex h-9 items-center justify-center rounded-md border border-gray-200 bg-white shadow-sm text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:border-gray-800"
              href="#">
              Take the Test
            </Link>
            <Link
              className="inline-flex h-9 items-center justify-center rounded-md border border-gray-200 bg-white shadow-sm text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:border-gray-800"
              href="https://psychcentral.com/health/letter-from-the-editor-you-are-safe-here">
              Read the Blog
            </Link>
            <Link
              className="inline-flex h-9 items-center justify-center rounded-md border border-gray-200 bg-white shadow-sm text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:border-gray-800"
              href="contact">
              Contact Us
            </Link>
          </div>
        </div>
      </header>
      <section className="py-12 md:py-24 lg:py-32">
        <div
          className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">How Are You Feeling Today?</h2>
            <p
              className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Take our online tests and assessments to understand your mental well-being.
            </p>
          </div>
          <div
            className="grid w-full grid-cols-1 gap-4 md:grid-cols-2 md:gap-8 lg:gap-12">
            <div className="mx-auto space-y-2 md:col-start-2 md:space-y-3">
              <h3 className="text-2xl font-bold">Anxiety Test</h3>
              <p className="text-sm text-gray-500 md:text-base dark:text-gray-400">
                Are you often worried or anxious? Take our test to find out.
              </p>
              <Link
                className="inline-flex h-9 items-center justify-center rounded-md border border-gray-200 bg-white shadow-sm text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:border-gray-800"
                href="#">
                Take the Test
              </Link>
            </div>
            <div className="mx-auto space-y-2 md:col-start-1 md:space-y-3">
              <h3 className="text-2xl font-bold">Depression Test</h3>
              <p className="text-sm text-gray-500 md:text-base dark:text-gray-400">
                Feeling down or hopeless? Our test can help you understand your mood.
              </p>
              <Link
                className="inline-flex h-9 items-center justify-center rounded-md border border-gray-200 bg-white shadow-sm text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:border-gray-800"
                href="#">
                Take the Test
              </Link>
            </div>
          </div>
        </div>
      </section>
      <section className="bg-gray-100 py-12 md:py-24 lg:py-32">
        <div
          className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">
              Let's Talk About Mental Health
            </h2>
            <p
              className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Our blog features articles, tips, and stories about mental health and well-being.
            </p>
          </div>
          <div className="grid w-full grid-cols-1 gap-6 md:grid-cols-3 md:gap-8">
            <div className="flex flex-col space-y-2">
              <div className="space-y-2">
                <h3 className="text-2xl font-bold">Understanding Bipolar Disorder</h3>
                <p className="text-gray-500 dark:text-gray-400">By John Smith</p>
              </div>
            </div>
            <div className="flex flex-col space-y-2">
              <img
                alt="Article cover"
                className="aspect-[2/1] overflow-hidden rounded-lg object-cover object-center"
                height="300"
                src="/placeholder.svg"
                width="600" />
              <div className="space-y-2">
                <h3 className="text-2xl font-bold">Coping with Stress: Tips for a Healthier Mind</h3>
                <p className="text-gray-500 dark:text-gray-400">By Emily Johnson</p>
              </div>
            </div>
            <div className="flex flex-col space-y-2">
              <img
                alt="Article cover"
                className="aspect-[2/1] overflow-hidden rounded-lg object-cover object-center"
                height="300"
                src="/placeholder.svg"
                width="600" />
              <div className="space-y-2">
                <h3 className="text-2xl font-bold">The Importance of Self-Care</h3>
                <p className="text-gray-500 dark:text-gray-400">By Sarah Adams</p>
              </div>
            </div>
          </div>
          <div className="flex justify-center mt-8">
            <Link
              className="inline-flex h-9 items-center justify-center rounded-md border border-gray-200 bg-white shadow-sm text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:border-gray-800"
              href="#">
              View All Posts
            </Link>
          </div>
        </div>
      </section>
      <section className="py-12 md:py-24 lg:py-32">
        <div
          className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Our Services</h2>
            <p
              className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              We offer counseling, therapy, and support services for those struggling with mental health issues.
            </p>
          </div>
          <div className="grid w-full grid-cols-1 gap-4 md:grid-cols-3 md:gap-8">
            <div className="mx-auto space-y-2">
              <img
                alt="Service cover"
                className="aspect-[16/9] overflow-hidden rounded-xl object-cover object-center"
                height="300"
                src="/placeholder.svg"
                width="600" />
              <div className="space-y-2">
                <h3 className="text-2xl font-bold">Therapy Sessions</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Professional counseling and therapy sessions with licensed therapists.
                </p>
                <Link
                  className="inline-flex h-9 items-center justify-center rounded-md border border-gray-200 bg-white shadow-sm text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:border-gray-800"
                  href="#">
                  Learn More
                </Link>
              </div>
            </div>
            <div className="mx-auto space-y-2">
              <img
                alt="Service cover"
                className="aspect-[16/9] overflow-hidden rounded-xl object-cover object-center"
                height="300"
                src="/placeholder.svg"
                width="600" />
              <div className="space-y-2">
                <h3 className="text-2xl font-bold">Mindfulness Workshops</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Interactive workshops to learn mindfulness and meditation techniques.
                </p>
                <Link
                  className="inline-flex h-9 items-center justify-center rounded-md border border-gray-200 bg-white shadow-sm text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:border-gray-800"
                  href="#">
                  Learn More
                </Link>
              </div>
            </div>
            <div className="mx-auto space-y-2">
              <img
                alt="Service cover"
                className="aspect-[16/9] overflow-hidden rounded-xl object-cover object-center"
                height="300"
                src="/placeholder.svg"
                width="600" />
              <div className="space-y-2">
                <h3 className="text-2xl font-bold">Support Groups</h3>
                <p className="text-gray-500 dark:text-gray-400">
                  Join peer-led support groups to connect with others facing similar challenges.
                </p>
                <Link
                  className="inline-flex h-9 items-center justify-center rounded-md border border-gray-200 bg-white shadow-sm text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:border-gray-800"
                  href="#">
                  Learn More
                </Link>
              </div>
            </div>
          </div>
        </div>
      </section>
      <section id="contact" className="bg-gray-100 py-12 md:py-24 lg:py-32">
        <div
          className="container grid items-center justify-center gap-4 px-4 text-center md:px-6">
          <div className="space-y-3">
            <h2 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl">Contact Us</h2>
            <p
              className="mx-auto max-w-[700px] text-gray-500 md:text-xl/relaxed lg:text-base/relaxed xl:text-xl/relaxed dark:text-gray-400">
              Ready to take the next step? Reach out to us for more information or to schedule an appointment.
            </p>
          </div>
          <div className="mx-auto max-w-[400px] space-y-4">
            <div className="grid grid-cols-2 gap-4">
              <Input placeholder="First Name" />
              <Input placeholder="Last Name" />
            </div>
            <Input placeholder="Email" type="email" />
            <Input as="textarea" className="h-[200px]" placeholder="Message" />
            <Button>Submit</Button>
          </div>
        </div>
      </section>
      <footer className="border-t border-gray-200 dark:border-gray-800">
        <div
          className="container grid items-center justify-center gap-4 px-4 py-12 text-center md:grid-cols-3 md:px-6 md:py-16 lg:grid-cols-3 lg:gap-8 lg:py-24 xl:grid-cols-3 xl:gap-10 xl:py-32">
          <div className="space-y-2">
            <p className="text-sm text-gray-500 dark:text-gray-400">© 2023 Get Out There</p>
          </div>
          <div className="space-y-2">
            <Link className="font-medium underline" href="#">
              Privacy Policy
            </Link>
            <Link className="font-medium underline" href="#">
              Terms & Conditions
            </Link>
          </div>
          <div className="space-y-2">
            <Link
              className="inline-flex h-9 items-center justify-center rounded-md border border-gray-200 bg-white shadow-sm text-sm font-medium transition-colors hover:bg-gray-100 hover:text-gray-900 dark:border-gray-800 dark:bg-gray-950 dark:hover:bg-gray-800 dark:hover:text-gray-50 dark:border-gray-800"
              href="#">
              Contact Us
            </Link>
          </div>
        </div>
      </footer>
    </div>)
  );
}
